### Login ### 

POST http://localhost:8080/api/v1/admin/login 
Content-Type: application/json

{
      "email": "rohit21oct85@gmail.com",
      "password": "password"
}

### Update Module ###
POST http://localhost:8080/api/v1/master-module/update-all

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmE5MzY4ZTVhMWZmMzc3NTVmODVkZSIsInJvbGUiOjEsImlhdCI6MTYyODg1Nzc1NiwiZXhwIjoxNjMxNDQ5NzU2fQ.gmy8WYziVIIg_qcV4SyUfXKxFJPnmEP9BTHOanxPfeA



### Add Fields ###
POST http://localhost:3000/api/v1/admin/add-fields
Content-Type: application/json

### delete Chapters ###
POST http://localhost:8080/api/v1/chapter/delete-chapters
Content-Type: application/json

{
      "isbn":"9781323156759",
      "chapter_no":"2"
}

### dashboard ###
GET https://admin.crazyforstudy.com/api/v1/master-admin/statics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmE5MzY4ZTVhMWZmMzc3NTVmODVkZSIsInJvbGUiOjEsImlhdCI6MTYyODg1Nzc1NiwiZXhwIjoxNjMxNDQ5NzU2fQ.gmy8WYziVIIg_qcV4SyUfXKxFJPnmEP9BTHOanxPfeA


